<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../css/main.css">
    <link rel="stylesheet" href="../css/register.css">
    <title>Document</title>
</head>
<body >

<h1>Dear, ${username}!</h1>
<h3>Your letter received, expect a response from our experts.</h3>
<h5>${text}</h5>
<h6>${time}</h6>


</body>
</html>